import { useEffect, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { addEditComment, approveEdit, getEditingDetails, requestChanges, updateEditingStatus } from '../services/editing';
import { EDIT_STATUS_LABELS } from '../constants/video-workflow';
import type { EditingDetails as Details, EditVersionStatus, Video } from '../types/domain';

const format=(value:string|null)=>value?new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date(value)):'—';
export function EditingDetails({video,user}:{video:Video;user:User|null}) {
  const [details,setDetails]=useState<Details|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState('');
  const load=async()=>{setLoading(true);setError(null);try{setDetails(await getEditingDetails(video));}catch{setError('Could not load editing details.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[video.id,video.next_action_version_id]);
  const mutate=async(operation:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await operation();await load();}catch(value){setError(value instanceof Error?value.message:'Could not save editing changes.');}finally{setBusy(false);}};
  if(loading)return <div className="py-4 text-sm text-slate-500" role="status">Loading editing details…</div>;
  if(error&&!details)return <div className="py-4 text-sm text-red-700" role="alert">Could not load editing details. <button className="btn-text" onClick={()=>void load()}>Retry</button></div>;
  const version=details?.activeVersion;if(!version)return <div className="py-4 text-sm text-slate-500">No editing version has been created yet.</div>;
  const profileName=(id:string|null)=>id?(details?.profilesById[id]?.display_name||'Unknown user'):'Unknown user';
  return <div className="mt-4 border-t border-slate-200 pt-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="eyebrow">Version {version.version_number}</div><div className="font-semibold">{EDIT_STATUS_LABELS[version.status]}</div></div><label className="grid gap-1 text-xs font-medium text-slate-500">Status<select className="input min-h-9 py-1" value={version.status} disabled={busy} onChange={(event)=>user&&void mutate(()=>updateEditingStatus(video,version,event.target.value as EditVersionStatus,user.id))}>{Object.entries(EDIT_STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><div className="mt-3 grid gap-1 text-xs font-medium text-slate-500"><span>Assigned to {profileName(version.assigned_editor)}</span><span>Created by {profileName(version.created_by)} · {format(version.created_at)}</span>{video.next_action_note&&<span>{video.next_action_note}</span>}</div>{video.next_action==='review_edit'&&user&&<div className="mt-4 flex gap-2"><button className="btn-secondary" disabled={busy} onClick={()=>void mutate(()=>requestChanges(video))}>Request Changes</button><button className="btn-primary" disabled={busy} onClick={()=>void mutate(()=>approveEdit(video,user.id))}>Approve Edit</button></div>}{error&&<div className="mt-3 text-xs text-red-700">{error}</div>}<div className="mt-5"><div className="eyebrow">Discussion</div>{details?.comments.length?details.comments.map((comment)=><article key={comment.id} className="border-b border-slate-100 py-3"><div className="flex flex-wrap justify-between gap-2 text-xs"><strong className="font-semibold">{comment.author_name_snapshot}</strong><span className="font-medium text-slate-400">{comment.author_role_snapshot} · {format(comment.created_at)}</span></div><p className="mt-1 text-sm text-slate-600">{comment.message}</p></article>):<div className="py-3 text-sm text-slate-500">No comments yet.</div>}{user&&<form className="mt-3 flex items-end gap-2" onSubmit={(event)=>{event.preventDefault();void mutate(async()=>{await addEditComment(version.id,user,details?.profilesById[user.id]||null,message);setMessage('');});}}><textarea className="input min-h-20 flex-1 resize-y" value={message} onChange={(event)=>setMessage(event.target.value)} placeholder="Add a comment" required/><button className="btn-secondary" disabled={busy}>Add comment</button></form>}</div></div>;
}
