import { useEffect, useState } from 'react';
import logoUrl from '../../assets/logo_new.png';
import { sendLoginLink } from '../services/auth';

const validEmail=(email:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
const messageFor=(error:unknown)=>{const message=error instanceof Error?error.message.toLowerCase():'';if(message.includes('rate')||message.includes('seconds'))return'Please wait before requesting another login link.';if(message.includes('fetch')||message.includes('network'))return"We couldn't reach the server. Check your connection and try again.";return"We couldn't send the login link. Please try again.";};

export function LoginPage() {
  const [email,setEmail]=useState('');const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [status,setStatus]=useState<string|null>(null);const [seconds,setSeconds]=useState(0);
  useEffect(()=>{if(!seconds)return;const timer=window.setInterval(()=>setSeconds((value)=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer);},[seconds]);
  const submit=async(isResend=false)=>{const normalized=email.trim().toLowerCase();if(!validEmail(normalized)){setError('Enter a valid email address.');return;}setBusy(true);setError(null);try{await sendLoginLink(normalized);setEmail(normalized);setSent(true);setSeconds(60);setStatus(isResend?'A new login link was sent.':'A login link was sent. It may take a moment to arrive.');}catch(value){setError(messageFor(value));}finally{setBusy(false);}};
  return <main className="grid min-h-screen place-items-center px-4 py-8"><section className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-xl shadow-slate-900/5 max-sm:p-6" aria-labelledby="auth-title"><img className="mx-auto mb-4 h-16 w-16 object-contain" src={logoUrl} alt="Giggle Sprouts logo"/><h1 id="auth-title" className="text-center text-2xl font-bold">{sent?'Check your email':'Welcome to SproutOps'}</h1>{sent?<><p className="mt-3 text-center leading-6 text-slate-600">We sent a secure login link to:<br/><strong>{email}</strong></p><p className="mt-2 text-center text-sm text-slate-500">Open the email and click the link to continue in this window.</p></>:<p className="mt-2 text-center text-slate-500">Sign in with your email to continue.</p>}{!sent&&<form className="mt-6 grid gap-3" onSubmit={(event)=>{event.preventDefault();void submit();}}><label className="text-sm font-semibold" htmlFor="email-input">Email address</label><input id="email-input" className="input" type="email" autoComplete="email" value={email} onChange={(event)=>setEmail(event.target.value)} required/><button className="btn-primary" disabled={busy}>{busy?'Sending…':'Send login link'}</button></form>}{error&&<div className="mt-4 text-center text-sm text-red-700" role="alert">{error}</div>}{status&&<div className="mt-4 text-center text-sm text-slate-600" role="status">{status}</div>}{sent&&<div className="mt-5 grid gap-2"><button className="btn-secondary" disabled={busy||seconds>0} onClick={()=>void submit(true)}>{seconds?`Resend link in ${seconds}s`:'Resend login link'}</button><button className="btn-text" onClick={()=>{setSent(false);setStatus(null);}}>Use a different email</button></div>}</section></main>;
}
