import { useEffect, useRef, useState } from 'react';
import type { Project } from '../types/domain';

export function NewVideoModal({open,projects,activeProjectId,onClose,onCreate}:{open:boolean;projects:Project[];activeProjectId:string|null;onClose:()=>void;onCreate:(input:{title:string;description:string;projectId:string})=>Promise<void>}) {
  const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [projectId,setProjectId]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const inputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(!open)return;setTitle('');setDescription('');setProjectId(projects.some(({id})=>id===activeProjectId)?activeProjectId!:projects[0]?.id||'');setError(null);window.setTimeout(()=>inputRef.current?.focus());},[open,activeProjectId,projects]);
  useEffect(()=>{if(!open)return;const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy)onClose();};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[open,onClose,busy]);
  if(!open)return null;
  const validProject=projects.some(({id})=>id===projectId);
  return <div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/40 p-4 max-sm:items-end max-sm:p-0" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!busy)onClose();}}><section className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl max-sm:rounded-b-none" role="dialog" aria-modal="true" aria-labelledby="new-video-title"><div className="flex justify-between gap-3"><div><h2 id="new-video-title" className="text-xl font-bold">New Video</h2><p className="mt-1 text-sm text-slate-500">Create a fresh production workflow.</p></div><button className="grid h-9 w-9 place-items-center rounded-full bg-slate-100" onClick={onClose} aria-label="Close">×</button></div><form className="mt-5 grid gap-4" onSubmit={async(event)=>{event.preventDefault();if(!title.trim()||!validProject)return;setBusy(true);setError(null);try{await onCreate({title:title.trim(),description,projectId});onClose();}catch{setError('Could not create the video.');}finally{setBusy(false);}}}>{projects.length>1&&<label className="grid gap-1 text-sm font-medium">Project<select className="input" value={projectId} onChange={(event)=>setProjectId(event.target.value)}>{projects.map((project)=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label>}<label className="grid gap-1 text-sm font-medium">Video title<input ref={inputRef} className="input" value={title} onChange={(event)=>setTitle(event.target.value)} required/></label><label className="grid gap-1 text-sm font-medium">Description (optional)<textarea className="input min-h-24 resize-y" value={description} onChange={(event)=>setDescription(event.target.value)}/></label>{!projects.length&&<div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">You need access to an active project before creating a video.</div>}{error&&<div className="text-sm text-red-700">{error}</div>}<div className="flex justify-end gap-2"><button className="btn-secondary" type="button" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={busy||!validProject}>{busy?'Creating…':'Create Video'}</button></div></form></section></div>;
}
