import { archiveVideo, createVideo, getVideos, toggleVideoChecklist, updateVideo } from './services/videos.js';
import { addEditComment, approveEdit, getEditingDetails, requestChanges, updateEditingStatus } from './services/editing.js';
import { getSession, onAuthStateChange, sendLoginLink, signOut } from './services/auth.js';
import { EDIT_STATUS_LABELS, NEXT_ACTION_LABELS, VIDEO_STAGE_LABELS, deriveWorkflowItems, getChecklistUpdate } from './constants/video-workflow.js';
import logoUrl from '../assets/logo_new.png';

const state={session:null,isAuthLoading:true,authStep:'email',authEmail:'',authBusy:false,authError:null,authStatus:null,resendSeconds:0,videos:[],isLoading:false,loadError:null,modalOpen:false,isSaving:false,createError:null,createDraft:{title:'',description:''},expandedVideoId:null,expandedSections:{},mutationErrors:{},workflowPending:{},workflowErrors:{},editingByVideoId:{},editingLoading:{},editingErrors:{},editingPending:{},commentDrafts:{}};
const stageIcons={pre_production:'📝',production:'🎥',editing:'✂️',publishing:'🚀',completed:'✓',on_hold:'⏸'};
const pipeline=['pre_production','production','editing','publishing','completed'];
const skipLogin=import.meta.env.DEV&&import.meta.env.VITE_APP_MODE==='development';
const sectionKey=(videoId,section)=>`${videoId}:${section}`;
const escapeHtml=(value='')=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const formatDate=(value)=>value?new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date(value)):'—';
const formatDateTime=(value)=>value?new Intl.DateTimeFormat('en',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value)):'—';
const sortVideos=(videos)=>[...videos].sort((a,b)=>a.sequence_number-b.sequence_number);
const replaceVideo=(saved)=>{state.videos=sortVideos(state.videos.map((item)=>item.id===saved.id?{...item,...saved}:item));};
const currentUserId=()=>state.session?.user?.id||null;

const header=()=>`<header class="header"><div class="brand-row"><img class="brand-logo" src="${logoUrl}" alt="Giggle Sprouts logo"><div><div class="app-title">SproutOps</div><div class="header-copy">Production operating system</div></div></div><div class="header-actions"><button class="new-video-btn header-new-video-btn" type="button" data-action="open-modal">+ New Video</button><div class="account-control"><span class="account-email">${escapeHtml(state.session?.user?.email||'')}</span><button class="secondary-btn sign-out-btn" type="button" data-action="sign-out">Sign out</button></div></div></header>`;

function renderStages(video){return `<div class="stage-summary" aria-label="Production pipeline">${pipeline.map((stage)=>`<div class="stage-summary-item ${video.current_stage===stage?'current':''}"><span class="stage-symbol">${stageIcons[stage]}</span><span class="stage-state">${escapeHtml(VIDEO_STAGE_LABELS[stage])}</span></div>`).join('')}</div>`;}

function workflowItems(video,stage){
  try{return deriveWorkflowItems(video).filter((item)=>item.stage===stage);}
  catch(error){return {error:error.message};}
}

function renderWorkflowContent(video,stage){
  const result=workflowItems(video,stage);
  if(result.error)return `<div class="task-load-error" role="alert">${escapeHtml(result.error)}</div>`;
  const pending=Boolean(state.workflowPending[video.id]);
  return result.map((item)=>{
    const enabled=item.enabled&&!pending;
    return `<label class="task-row ${item.completed?'completed':''} ${item.current?'current-workflow-item':''}" title="${escapeHtml(item.label)}"><input class="task-check" type="checkbox" data-action="toggle-checklist" data-workflow-action="${item.key}" data-video-id="${video.id}" ${item.completed?'checked':''} ${enabled?'':'disabled'}><span class="task-label">${escapeHtml(item.label)}</span>${item.current?'<span class="workflow-current-label">Up next</span>':''}</label>`;
  }).join('')+(state.workflowErrors[video.id]?`<div class="task-update-error" role="status">${escapeHtml(state.workflowErrors[video.id])}</div>`:'');
}

function renderTaskSection(video,title,icon,stage){
  const expanded=Boolean(state.expandedSections[sectionKey(video.id,stage)]);
  return `<section class="detail-section"><button class="section-heading stage-${stage.replace('_','-')}" type="button" data-action="toggle-section" data-video-id="${video.id}" data-section-id="${stage}" aria-expanded="${expanded}"><span>${icon} ${title}</span><span class="section-chevron" aria-hidden="true">›</span></button>${expanded?`<div class="section-content">${renderWorkflowContent(video,stage)}</div>`:''}</section>`;
}

function profileName(details,id){return id?(details?.profilesById?.[id]?.display_name||'Unknown user'):'Unknown user';}

function renderComments(video,details){
  const version=details.activeVersion;
  if(!version)return'';
  const comments=details.comments||[];
  return `<div class="editing-discussion"><div class="eyebrow">Discussion</div>${comments.length?comments.map((comment)=>`<div class="edit-comment"><div class="comment-heading"><strong>${escapeHtml(comment.author_name_snapshot||'Unknown user')}</strong><span>${escapeHtml(comment.author_role_snapshot||'Team Member')} · ${formatDateTime(comment.created_at)}</span></div><p>${escapeHtml(comment.message)}</p></div>`).join(''):'<div class="section-empty">No comments yet.</div>'}<form class="comment-form" data-action="add-comment" data-video-id="${video.id}"><textarea class="form-input" name="message" rows="2" placeholder="Add a comment" required>${escapeHtml(state.commentDrafts[video.id]||'')}</textarea><button class="secondary-btn" type="submit" ${state.editingPending[video.id]?'disabled':''}>Add comment</button></form></div>`;
}

function renderEditingDetails(video){
  if(state.editingLoading[video.id])return '<div class="task-loading" role="status">Loading editing details…</div>';
  if(state.editingErrors[video.id])return `<div class="task-load-error" role="alert">Could not load editing details. <button class="text-btn" type="button" data-action="retry-editing" data-video-id="${video.id}">Retry</button></div>`;
  const details=state.editingByVideoId[video.id];
  if(!details?.activeVersion)return '<div class="section-empty">No editing version has been created yet.</div>';
  const version=details.activeVersion;
  const busy=Boolean(state.editingPending[video.id]);
  const statusOptions=Object.entries(EDIT_STATUS_LABELS).map(([value,label])=>`<option value="${value}" ${version.status===value?'selected':''}>${label}</option>`).join('');
  const reviewActions=video.next_action==='review_edit'?`<div class="review-actions"><button class="secondary-btn" type="button" data-action="request-changes" data-video-id="${video.id}" ${busy?'disabled':''}>Request Changes</button><button class="primary-btn" type="button" data-action="approve-edit" data-video-id="${video.id}" ${busy?'disabled':''}>Approve Edit</button></div>`:'';
  return `<div class="editing-content"><div class="editing-summary"><div><div class="eyebrow">Version ${version.version_number}</div><div class="version-name">${escapeHtml(EDIT_STATUS_LABELS[version.status]||'Unknown status')}</div></div><label class="status-field"><span>Status</span><select class="form-input" data-action="edit-status" data-video-id="${video.id}" ${busy?'disabled':''}>${statusOptions}</select></label></div><div class="editing-metadata"><span>Assigned to ${escapeHtml(profileName(details,version.assigned_editor))}</span><span>Created by ${escapeHtml(profileName(details,version.created_by))} · ${formatDate(version.created_at)}</span>${version.submitted_for_review_at?`<span>Submitted ${formatDateTime(version.submitted_for_review_at)}</span>`:''}${version.reviewed_at?`<span>Reviewed by ${escapeHtml(profileName(details,version.reviewed_by))} · ${formatDateTime(version.reviewed_at)}</span>`:''}${video.next_action_note?`<span>${escapeHtml(video.next_action_note)}</span>`:''}</div>${reviewActions}${state.editingErrors[`${video.id}:mutation`]?`<div class="inline-error">${escapeHtml(state.editingErrors[`${video.id}:mutation`])}</div>`:''}${renderComments(video,details)}</div>`;
}

function renderEditingSection(video){
  const expanded=Boolean(state.expandedSections[sectionKey(video.id,'editing')]);
  return `<section class="detail-section"><button class="section-heading stage-editing" type="button" data-action="toggle-section" data-video-id="${video.id}" data-section-id="editing" aria-expanded="${expanded}"><span>✂️ EDITING</span><span class="section-chevron" aria-hidden="true">›</span></button>${expanded?`<div class="section-content">${renderWorkflowContent(video,'editing')}${renderEditingDetails(video)}</div>`:''}</section>`;
}

function renderDetails(video){return `<div class="accordion-details"><div class="detail-workflow">${renderTaskSection(video,'PRE-PRODUCTION','📝','pre_production')}${renderTaskSection(video,'PRODUCTION','🎥','production')}${renderEditingSection(video)}${renderTaskSection(video,'PUBLISHING','🚀','publishing')}</div><div class="detail-panel"><div class="detail-grid"><div class="detail-item"><div class="detail-label">Updated</div><div class="detail-value">${formatDate(video.updated_at)}</div></div><div class="detail-item"><div class="detail-label">Current stage</div><div class="detail-value">${escapeHtml(VIDEO_STAGE_LABELS[video.current_stage]||'Unknown')}</div></div><div class="detail-item"><div class="detail-label">Up Next</div><div class="detail-value">${escapeHtml(NEXT_ACTION_LABELS[video.next_action]||'Unknown action')}</div></div><div class="detail-item"><div class="detail-label">Created</div><div class="detail-value">${formatDate(video.created_at)}</div></div></div><form class="edit-form" data-action="edit-video" data-video-id="${video.id}"><label class="form-field"><span>Video title</span><input class="form-input" name="title" value="${escapeHtml(video.title)}" required></label>${state.mutationErrors[video.id]?`<div class="inline-error">${escapeHtml(state.mutationErrors[video.id])}</div>`:''}<div class="form-actions"><button class="danger-btn" type="button" data-action="archive-video" data-video-id="${video.id}">Archive</button><button class="primary-btn" type="submit">Save changes</button></div></form></div></div>`;}

function renderCard(video){const expanded=state.expandedVideoId===video.id;const nextAction=NEXT_ACTION_LABELS[video.next_action]||'Unknown action';return `<section class="video-card-wrap"><button class="video-card" type="button" data-action="toggle-video" data-video-id="${video.id}" aria-expanded="${expanded}"><div class="video-card-top"><div class="video-title">#${video.sequence_number} ${escapeHtml(video.title)}</div><span class="chevron" aria-hidden="true">›</span></div><div class="video-facts"><span class="fact-card stage-fact"><span class="fact-icon" aria-hidden="true">🎬</span><span class="fact-copy"><span class="fact-label">Stage</span><span class="fact-value">${escapeHtml(VIDEO_STAGE_LABELS[video.current_stage]||'Unknown')}</span></span></span><span class="fact-card up-next-fact"><span class="fact-icon" aria-hidden="true">✅</span><span class="fact-copy"><span class="fact-label">Up Next</span><span class="fact-value">${escapeHtml(nextAction)}</span></span></span></div>${renderStages(video)}</button>${expanded?renderDetails(video):''}</section>`;}

function renderContent(){if(state.isLoading)return `<main class="video-list" aria-label="Loading videos"><div class="skeleton"></div><div class="skeleton"></div></main>`;if(state.loadError)return `<main><div class="state-card" role="alert"><h2>Could not load videos. Please try again.</h2><p>Check your connection or sign-in, then retry.</p><button class="primary-btn" type="button" data-action="retry-videos">Retry</button></div></main>`;if(!state.videos.length)return `<main><div class="state-card"><h2>No videos available</h2><p>Videos will appear here once they are added.</p><button class="primary-btn" type="button" data-action="open-modal">Create Video</button></div></main>`;return `<main class="video-list">${sortVideos(state.videos).map(renderCard).join('')}</main>`;}
function renderModal(){if(!state.modalOpen)return'';return `<div class="modal-backdrop" data-action="close-modal"><div class="modal-card" role="dialog" aria-modal="true" aria-label="Create new video"><div class="modal-header"><div><h2 class="modal-title">New Video</h2><p class="modal-copy">Create a fresh production workflow.</p></div><button class="modal-close" type="button" data-action="close-modal" aria-label="Close">×</button></div><form id="new-video-form" class="modal-form"><label class="form-field"><span>Video title</span><input id="video-title-input" class="form-input" name="title" value="${escapeHtml(state.createDraft.title)}" required></label><label class="form-field"><span>Description (optional)</span><textarea class="form-input" name="description" rows="3">${escapeHtml(state.createDraft.description)}</textarea></label>${state.createError?`<div class="inline-error">${escapeHtml(state.createError)}</div>`:''}<div class="modal-actions"><button class="secondary-btn" type="button" data-action="close-modal">Cancel</button><button class="primary-btn" type="submit" ${state.isSaving?'disabled':''}>${state.isSaving?'Creating…':'Create Video'}</button></div></form></div></div>`;}
function renderAuthLoading(){return `<main class="auth-shell" aria-busy="true"><div class="auth-card auth-loading"><img class="auth-logo" src="${logoUrl}" alt=""><div class="app-title">SproutOps</div><p>Restoring your session…</p></div></main>`;}
function renderLogin(){const message=state.authError?`<div id="auth-message" class="auth-message auth-error" role="alert" tabindex="-1">${escapeHtml(state.authError)}</div>`:state.authStatus?`<div id="auth-message" class="auth-message" role="status">${escapeHtml(state.authStatus)}</div>`:'';if(state.authStep==='link-sent')return `<main class="auth-shell"><section class="auth-card" aria-labelledby="auth-title"><img class="auth-logo" src="${logoUrl}" alt="Giggle Sprouts logo"><h1 id="auth-title">Check your email</h1><p>We sent a secure login link to:<br><strong>${escapeHtml(state.authEmail)}</strong></p><p>Open the email and click the link to continue to SproutOps.</p>${message}<div class="auth-secondary-actions"><button class="secondary-btn" type="button" data-action="resend-link" ${state.authBusy||state.resendSeconds>0?'disabled':''}>${state.resendSeconds>0?`Resend link in ${state.resendSeconds}s`:'Resend login link'}</button><button class="text-btn" type="button" data-action="change-email">Use a different email</button></div></section></main>`;return `<main class="auth-shell"><section class="auth-card" aria-labelledby="auth-title"><img class="auth-logo" src="${logoUrl}" alt="Giggle Sprouts logo"><h1 id="auth-title">Welcome to SproutOps</h1><p>Sign in with your email to continue.</p><form id="email-form" class="auth-form" aria-busy="${state.authBusy}"><label for="email-input">Email address</label><input id="email-input" class="form-input" name="email" type="email" autocomplete="email" value="${escapeHtml(state.authEmail)}" aria-describedby="auth-message" required><button class="primary-btn" type="submit" ${state.authBusy?'disabled':''}>${state.authBusy?'Sending…':'Send login link'}</button></form>${message}</section></main>`;}

function render(){if(!skipLogin&&state.isAuthLoading)document.getElementById('app').innerHTML=renderAuthLoading();else if(!skipLogin&&!state.session)document.getElementById('app').innerHTML=renderLogin();else document.getElementById('app').innerHTML=`<div class="page-shell">${header()}${renderContent()}</div><button class="new-video-btn new-video-fab" type="button" data-action="open-modal" aria-label="New Video">+</button>${renderModal()}`;bindEvents();}

async function loadVideos(){if(!skipLogin&&!state.session)return;state.isLoading=true;state.loadError=null;render();try{state.videos=sortVideos(await getVideos());}catch(error){console.error('Could not load videos:',error);state.loadError=error;}finally{state.isLoading=false;render();}}
async function loadEditing(videoId){const video=state.videos.find(({id})=>id===videoId);if(!video)return;state.editingLoading[videoId]=true;delete state.editingErrors[videoId];render();try{state.editingByVideoId[videoId]=await getEditingDetails(video);}catch(error){console.error('Could not load editing details:',error);state.editingErrors[videoId]=error.message||'Could not load editing details.';}finally{delete state.editingLoading[videoId];render();}}

async function toggleChecklist(videoId,actionKey,isCompleted){if(state.workflowPending[videoId])return;const video=state.videos.find(({id})=>id===videoId);if(!video)return;const previous={...video};state.workflowPending[videoId]=true;delete state.workflowErrors[videoId];try{replaceVideo({...video,...getChecklistUpdate(video,actionKey,isCompleted)});render();const saved=await toggleVideoChecklist(videoId,video,actionKey,isCompleted);replaceVideo(saved);}catch(error){replaceVideo(previous);state.workflowErrors[videoId]=error.message||'Could not save checklist.';}finally{delete state.workflowPending[videoId];render();}}
async function editingMutation(videoId,operation){if(state.editingPending[videoId])return;const video=state.videos.find(({id})=>id===videoId);if(!video)return;state.editingPending[videoId]=true;delete state.editingErrors[`${videoId}:mutation`];render();try{const result=await operation(video);if(result?.video)replaceVideo(result.video);await loadEditing(videoId);}catch(error){state.editingErrors[`${videoId}:mutation`]=error.message||'Could not save editing changes.';await loadEditing(videoId);}finally{delete state.editingPending[videoId];render();}}

async function requireAuthenticated(){return skipLogin||Boolean(state.session);}
async function openModal(){if(!await requireAuthenticated())return;state.modalOpen=true;state.createError=null;state.createDraft={title:'',description:''};render();document.getElementById('video-title-input')?.focus();}
function closeModal(){if(state.isSaving)return;state.modalOpen=false;state.createError=null;state.createDraft={title:'',description:''};render();}
const validEmail=(email)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
function authErrorMessage(error,fallback){const message=String(error?.message||'').toLowerCase();if(message.includes('rate')||message.includes('seconds'))return'Please wait before requesting another login link.';if(message.includes('fetch')||message.includes('network'))return"We couldn't reach the server. Check your connection and try again.";return fallback;}
let resendTimer;
function startResendCooldown(){clearInterval(resendTimer);state.resendSeconds=60;resendTimer=setInterval(()=>{state.resendSeconds=Math.max(0,state.resendSeconds-1);if(!state.resendSeconds)clearInterval(resendTimer);render();},1000);}
async function requestLoginLink(email,isResend=false){if(state.authBusy||state.resendSeconds>0&&isResend)return;state.authBusy=true;state.authError=null;state.authStatus=null;render();try{await sendLoginLink(email);state.authEmail=email;state.authStep='link-sent';state.authStatus=isResend?'A new login link was sent.':'A login link was sent. It may take a moment to arrive.';startResendCooldown();}catch(error){console.error('Could not send login link:',error?.message||'Unknown authentication error');state.authError=authErrorMessage(error,"We couldn't send the login link. Please try again.");}finally{state.authBusy=false;render();document.getElementById('auth-message')?.focus();}}

function bindEvents(){
  const emailForm=document.getElementById('email-form');if(emailForm)emailForm.addEventListener('submit',async(event)=>{event.preventDefault();const email=new FormData(emailForm).get('email')?.toString().trim().toLowerCase()||'';state.authEmail=email;if(!validEmail(email)){state.authError='Enter a valid email address.';state.authStatus=null;render();document.getElementById('auth-message')?.focus();return;}await requestLoginLink(email);});
  document.querySelector('[data-action="resend-link"]')?.addEventListener('click',()=>requestLoginLink(state.authEmail,true));
  document.querySelector('[data-action="change-email"]')?.addEventListener('click',()=>{clearInterval(resendTimer);state.authStep='email';state.authError=null;state.authStatus=null;state.resendSeconds=0;render();document.getElementById('email-input')?.focus();});
  document.querySelector('[data-action="sign-out"]')?.addEventListener('click',async()=>{try{await signOut();state.session=null;state.videos=[];state.expandedVideoId=null;state.modalOpen=false;state.authStep='email';render();}catch(error){console.error('Could not sign out:',error);}});
  document.querySelectorAll('[data-action="open-modal"]').forEach((button)=>button.addEventListener('click',openModal));
  document.querySelectorAll('[data-action="close-modal"]').forEach((element)=>element.addEventListener('click',(event)=>{if(event.target===event.currentTarget||event.target.closest('button'))closeModal();}));
  document.querySelectorAll('[data-action="retry-videos"]').forEach((button)=>button.addEventListener('click',loadVideos));
  document.querySelectorAll('[data-action="retry-editing"]').forEach((button)=>button.addEventListener('click',()=>loadEditing(button.dataset.videoId)));
  document.querySelectorAll('[data-action="toggle-checklist"]').forEach((checkbox)=>checkbox.addEventListener('change',()=>toggleChecklist(checkbox.dataset.videoId,checkbox.dataset.workflowAction,checkbox.checked)));
  document.querySelectorAll('[data-action="toggle-video"]').forEach((button)=>button.addEventListener('click',()=>{state.expandedVideoId=state.expandedVideoId===button.dataset.videoId?null:button.dataset.videoId;render();}));
  document.querySelectorAll('[data-action="toggle-section"]').forEach((button)=>button.addEventListener('click',()=>{const key=sectionKey(button.dataset.videoId,button.dataset.sectionId);state.expandedSections[key]=!state.expandedSections[key];render();if(button.dataset.sectionId==='editing'&&state.expandedSections[key]&&!state.editingByVideoId[button.dataset.videoId])loadEditing(button.dataset.videoId);}));
  document.querySelectorAll('[data-action="edit-status"]').forEach((select)=>select.addEventListener('change',()=>{const videoId=select.dataset.videoId;const details=state.editingByVideoId[videoId];editingMutation(videoId,(video)=>updateEditingStatus(video,details.activeVersion,select.value,currentUserId()));}));
  document.querySelectorAll('[data-action="request-changes"]').forEach((button)=>button.addEventListener('click',()=>editingMutation(button.dataset.videoId,requestChanges)));
  document.querySelectorAll('[data-action="approve-edit"]').forEach((button)=>button.addEventListener('click',()=>editingMutation(button.dataset.videoId,(video)=>approveEdit(video,currentUserId()))));
  document.querySelectorAll('form[data-action="add-comment"]').forEach((form)=>form.addEventListener('submit',async(event)=>{event.preventDefault();const videoId=form.dataset.videoId;const message=new FormData(form).get('message')?.toString()||'';state.commentDrafts[videoId]=message;const details=state.editingByVideoId[videoId];await editingMutation(videoId,async(video)=>{const user=state.session?.user;if(!user)throw new Error('Sign in is required to comment');await addEditComment(details.activeVersion.id,user,details.profilesById[user.id],message);state.commentDrafts[videoId]='';return{video};});}));
  document.querySelectorAll('form[data-action="edit-video"]').forEach((form)=>form.addEventListener('submit',async(event)=>{event.preventDefault();if(!await requireAuthenticated())return;const id=form.dataset.videoId;const data=new FormData(form);const title=data.get('title')?.toString().trim();if(!title)return;try{const updated=await updateVideo(id,{title});replaceVideo(updated);delete state.mutationErrors[id];}catch(error){state.mutationErrors[id]='Could not save the changes.';}render();}));
  document.querySelectorAll('[data-action="archive-video"]').forEach((button)=>button.addEventListener('click',async()=>{if(!await requireAuthenticated())return;const id=button.dataset.videoId;if(!window.confirm('Archive this video? It will be removed from the active board but retained in the database.'))return;try{await archiveVideo(id);state.videos=state.videos.filter((video)=>video.id!==id);state.expandedVideoId=null;}catch(error){state.mutationErrors[id]='Could not archive the video.';}render();}));
  const form=document.getElementById('new-video-form');if(form)form.addEventListener('submit',async(event)=>{event.preventDefault();if(!await requireAuthenticated())return;const data=new FormData(form);const title=data.get('title')?.toString().trim();const description=data.get('description')?.toString()||'';if(!title)return;state.createDraft={title,description};state.isSaving=true;state.createError=null;render();try{const created=await createVideo({title,description});state.videos=sortVideos([...state.videos,created]);state.modalOpen=false;state.createDraft={title:'',description:''};}catch(error){state.createError='Could not create the video.';}finally{state.isSaving=false;render();}});
}

document.addEventListener('keydown',(event)=>{if(event.key==='Escape'&&state.modalOpen)closeModal();});
render();
const unsubscribeAuth=onAuthStateChange((session)=>{const hadSession=Boolean(state.session);state.session=session;state.authBusy=false;if(!session){state.videos=[];state.editingByVideoId={};state.modalOpen=false;state.expandedVideoId=null;}if(!state.isAuthLoading){render();if(session&&!hadSession)loadVideos();}});
window.addEventListener('beforeunload',unsubscribeAuth,{once:true});
async function initializeAuth(){try{state.session=await getSession();}catch(error){console.error('Could not restore session:',error?.message||'Unknown authentication error');state.session=null;}finally{state.isAuthLoading=false;render();}if(skipLogin||state.session)await loadVideos();}
initializeAuth();
